server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
    # 如果前端请求带参 ?trace=true 则会显示 trace 字段
    include-stacktrace: on_param
  forward-headers-strategy: framework

spring:
  application:
    name: biz-service
  profiles:
    active: @activatedProfile@
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: true
  data:
    redis:
      database: 0
      host: ${REDIS_HOST:localhost}
      port: 6379
      password:
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0

management:
  endpoints:
    access:
      default: read_only

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    doc-expansion: alpha

sa-token:
  is-log: true
  sso-client:
    client: console-cli
    server-url: http://localhost:8080
    is-http: true
    secret-key: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor

app:
  datasource:
    biz:
      url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:5432/sa
      jdbcUrl: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:5432/sa
      username: root
      password: ${POSTGRESQL_ROOT_PASSWORD:example}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 100
        minimum-idle: 30
      liquibase:
        change-log: db/changelog/changelog-master.xml
