services:

  postgres:
    image: postgres:alpine3.22
    restart: always
    command: postgres -c 'max_connections=250'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
    ports:
      - "5432:5432"
    volumes:
      - ./init-postgres:/docker-entrypoint-initdb.d

  redis:
    image: redis:8.0.3-alpine
    restart: always
    ports:
      - "6379:6379"